config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :coupons
  post 'subscriptions/expire', to: 'subscriptions#expire'
  get 'products/:id', to: 'products#show', :as => :products
  get 'invite', to: 'high_voltage/pages#show', id: 'invitations'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
  mount StripeEvent::Engine, at: '/stripe'
  root :to => 'visitors#index'
end

app/models/video.rb
class Video < ApplicationRecord
  enum level: [:free, :beginner, :advanced]
  has_many :resources, validate: false
  has_many :relateds, validate: false
  accepts_nested_attributes_for :relateds, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :resources, reject_if: :all_blank, allow_destroy: true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, :except => :show
  before_action :authenticate_user!, only: [:show], :unless => :free_video?
  before_action :current_subscriber?, only: [:show]


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.order(date: :desc).page(params[:page]).per(20)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
   @video = Video.find(params[:id])
   @relateds = []
   @video.relateds.each do |item|
     unless item.wistia.blank?
       @relateds << Video.where(wistia: item.wistia).first
     end
   end
 end

  # GET /videos/new
  def new
    @video = Video.new
    @video.relateds.new
    @video.resources.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.relateds.build
    @video.resources.build
    # obtain video metadata using the Wistia API
    Rails.logger.info("obtaining metadata from Wistia API for #{@video.wistia}")
    media = Wistia::Media.find(@video.wistia)
    @video.title = media.name
    @video.description = ActionController::Base.helpers.strip_tags(media.description)
    @video.duration = (media.duration.to_i / 60) % 60
    @video.thumbnail_url = media.thumbnail.url

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Created video listing.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    Rails.logger.info("updating the thumbnail URL using the Wistia API for #{@video.wistia}")
    media = Wistia::Media.find(@video.wistia)
    @video.thumbnail_url = media.thumbnail.url
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_path, notice: 'Updated video listing.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Deleted video listing.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title,
                                      :level, :date, :duration, :presenter,
                                      relateds_attributes: [ :id, :wistia, :_destroy ],
                                      resources_attributes: [ :id, :url, :text, :description, :_destroy ]
                                      )
    end

    def current_subscriber?
      if user_signed_in? && current_user.expired?
        redirect_to root_path, :alert => "Subscription has
          expired for #{current_user.email}.
          Would you like to renew?"
      end
    end

    def admin_only
      unless current_user.nil?
        unless current_user.admin?
          redirect_to :back, :alert => "Access denied."
        end
      else
        redirect_to root_path, :alert => "Please sign in."
      end
    end

    def free_video?
      @video.free?
    end
end

app/views/videos/_form.html.erb
<%= form_for(@video, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @video.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h4>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Wistia ID", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :wistia, class: "form-control narrow-field" %>
    </div>
  </div>
  <% if controller.action_name == 'edit' %>
    <div class="form-group">
      <%= f.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label 'Minutes', class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :duration, class: "form-control narrow-field" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :presenter, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :presenter, value: 'AsiaG', class: "form-control narrow-field" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :level, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:level, Video.levels.keys.map {|level| [level.titleize,level]}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date, class: "form-control" %>
    </div>
  </div>
  <%= f.label :related, class: "col-sm-2 control-label" %>
  <div class="col-sm-10" id='relateds'>
    <%= f.fields_for :relateds do |related| %>
      <%= render 'related_fields', :f => related %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add a related video', f, :relateds, class: "col-sm-4" %>
    </div>
  </div>
  <%= f.label :resources, class: "col-sm-2 control-label" %>
  <div class="col-sm-10" id='resources'>
    <%= f.fields_for :resources do |resource| %>
      <%= render 'resource_fields', :f => resource %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add a resource', f, :resources, class: "col-sm-4" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <br />
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/videos/_related_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label 'ID' %>
    <%= f.text_field :wistia %>
    <%= link_to_remove_association 'remove', f %>
  </div>
</div>

app/views/videos/_resource_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
    <br/>
    <%= f.label :text %>
    <%= f.text_field :text %>
    <br/>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br/>
    <%= link_to_remove_association 'remove', f %>
  </div>
</div>

app/views/videos/_video.html.erb
<%= link_to(video) do %>
  <div class="row">
    <div class="col-sm-2 col-xs-12">
      <img class="img-responsive" src="https://embed-ssl.wistia.com/deliveries/400841c93e1bcd040fea50f3e6ad3ff314e7a64e.jpg?image_crop_resized=200x120" alt="" width="100" height="60">
    </div>
    <div class="col-sm-9 col-xs-10">
      <h3 style="margin-top:0px"><%= video.title unless video.title.nil? %><br></h3>
      <p class="text-muted">
        <small>
          <%= render partial: 'videolink', locals: {video: video} %>
          &nbsp;
          <time datetime="<%= video.date %>"><%= video.date.to_formatted_s(:long) unless video.date.nil? %></time>
        </small>
      </p>
      <p class="text-muted">
        <%= video.description unless video.description.nil? %>
      </p>
    </div>
  </div>
<% end %>

app/views/videos/_videolink.html.erb
<% if video.free? %>
  <span class="btn btn-primary btn-xs">Free</span>
<% else %>
  <% if user_signed_in? %>
    <% if current_user.expired? %>
        <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#purchaseModal">Renew</a>
    <% else %>
      <%= link_to("View", video, :class => "btn btn-success btn-xs") %>
    <% end %>
  <% else %>
    <a href="#" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#purchaseModal">Sign Up</a>
  <% end %>
<% end %>

app/views/videos/_whats_next.html.erb
<% unless video.nil? %>
  <%= link_to(video) do %>
    <% unless video.thumbnail_url.nil? %>
      <div class="row">
        <div class="col-xs-12 clearfix">
          <img class="img-responsive pull-left" src="<%= video.thumbnail_url %>" alt="" width="200">
          <br/>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <br/>
        <h4 style="margin-top:0px">
          <%= render partial: 'whatsnextlink', locals: {video: video} %>&nbsp;<%= video.title unless video.title.nil? %>
        <br /></h4>
        <p class="text-muted">
          <small>
          <%= video.description unless video.description.nil? %>
          </small>
        </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/videos/_whatsnextlink.html.erb
<% if video.free? %>
  <span class="btn btn-primary btn-xs">Free</span>
<% else %>
  <% if user_signed_in? %>
    <% if current_user.expired? %>
        <%= link_to('Renew', new_user_registration_path, :class => "btn btn-danger btn-xs") %>
    <% else %>
      <%= link_to("View", video, :class => "btn btn-success btn-xs") %>
    <% end %>
  <% else %>
    <%= link_to('Sign Up', new_user_registration_path, :class => "btn btn-danger btn-xs") %>
  <% end %>
<% end %>

app/views/videos/edit.html.erb
<div class="midform">
  <div class="page-header">
    <%= link_to videos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <%= link_to @video, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Show
    <% end %>
    <h1>Edit</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/videos/index.html.erb
<div class="page-header">
  <%= link_to new_video_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Video
  <% end %>
  <h1>Videos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Date</th>
            <th>Level</th>
            <th>Title</th>
            <th>Description</th>
            <th>Wistia ID</th>
            <th>Duration</th>
            <th>Presenter</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @videos) do |video| %>
            <td><%= video.date %></td>
            <td><%= video.level %></td>
            <td><strong><%= video.title %></strong></td>
            <td><%= video.description %></td>
            <td><%= video.wistia %></td>
            <td><%= video.duration %></td>
            <td><%= video.presenter %></td>
            <td>
                <%= link_to video, class: 'btn btn-primary btn-xs' do %>
                  <span class="glyphicon glyphicon-info-sign"></span>
                <% end %>
            </td>
            <td>
                <%= link_to edit_video_path(video), class: 'btn btn-primary btn-xs' do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>
            </td>
            <td>
                <%= link_to('<i class="glyphicon glyphicon-remove-sign"> </i>'.html_safe, video_path(video), :data => { :confirm => "Are you sure?" }, :method => :delete, class: 'btn-xs') %>
            </td>
      <% end %>
    </tbody>
  </table>
  <br />
  <br />
  <%= paginate @videos %>
</div>

app/views/videos/new.html.erb
<div class="midform">
  <div class="page-header">
    <%= link_to videos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Back
    <% end %>
    <h1>New video listing</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/videos/show.html.erb
<div class="container">
   <div class="row">
       <div class="col-md-8">
          <h2><%= @video.title unless @video.title.nil? %>
            <% if signed_in? %>
              <% if current_user.admin? %>
                <%= link_to edit_video_path(@video), class: 'btn btn-primary' do %>
                  <span class="glyphicon glyphicon-info-edit"></span>
                  Edit
                <% end %>
              <% end %>
            <% end %>
          </h2>
           <p class="text-muted">
             <time datetime="<%= @video.date %>" itemprop="datePublished"><%= @video.date.to_formatted_s(:long) unless @video.date.nil? %></time>
             &middot;
             <%= @video.level.titlecase unless @video.level.nil? %>
             &middot;
             <%= @video.duration unless @video.duration.nil? %> minutes
             &middot;
             <%= @video.presenter unless @video.presenter.nil? %>
           </p>
           <script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>
           <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;">
             <div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;">
               <div class="wistia_embed wistia_async_<%= @video.wistia %> videoFoam=true" style="height:100%;width:100%">&nbsp;
               </div>
             </div>
           </div>
       </div>
       <div class="col-md-4">
          <% unless @relateds.empty? %>
            <h3 style="padding-left:35px;">Watch Next</h3>
            <ul>
            <% @relateds.each do |video| %>
              <%= render partial: 'whats_next', locals: {video: video} %>
            <% end %>
            </ul>
          <% end %>
        </div>
   </div>
</div>
<div class="container">
      <hr />
      <h3 class="text-muted">Overview</h3>
      <p><%= @video.description unless @video.description.nil? %></p>
      <hr />
      <h3 class="text-muted">Resources</h3>
      <ul>
      <% @video.resources.each do |resource| %>
      <li><%= link_to resource.text, resource.url %> <%=resource.description %></li>
      <% end %>
      </ul>
      <hr />
      <div id="disqus_thread"></div>
      <script>
          /**
           *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
           *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
           */
          /*
          var disqus_config = function () {
              this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
              this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };
          */
          (function() {  // DON'T EDIT BELOW THIS LINE
              var d = document, s = d.createElement('script');

              s.src = '//fullstackvideos.disqus.com/embed.js';

              s.setAttribute('data-timestamp', +new Date());
              (d.head || d.body).appendChild(s);
          })();
      </script>
</div>

<hr />