config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :coupons
  post 'subscriptions/expire', to: 'subscriptions#expire'
  get 'products/:id', to: 'products#show', :as => :products
  get 'invite', to: 'high_voltage/pages#show', id: 'invitations'
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
  mount StripeEvent::Engine, at: '/stripe'
  root :to => 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= smart_link_to 'Subscription', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= smart_link_to 'Sign in', new_user_session_path %></li>
  <li><%= smart_link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Coupons', coupons_path %></li>
    <li><%= link_to 'Videos', videos_path %></li>
  <% end %>
<% end %>
<li><%= smart_link_to 'Suggestions', page_path('suggestions') %></li>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('fullstackvideos.png'), root_path, class: 'navbar-left' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'More Videos', root_url(anchor: 'videos') %></li>
<li><%= smart_link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fullstack Video Tutorials" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn to code with weekly free videos from AsiaG and Daniel Kehoe." %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <% if user_signed_in? %>
      <script type="text/javascript">
        analytics.identify('<%= current_user.id %>', {
          name: '<%= current_user.name %>',
          email: '<%= current_user.email %>'
        });
      </script>
    <% end %>
  </body>
</html>